import time
from contextlib import contextmanager
from pathlib import Path

from fastapi.testclient import TestClient

from oracle_relationship_discovery.analysis.service import AnalysisResult
from oracle_relationship_discovery.gui.app import create_app
from oracle_relationship_discovery.gui.services.oracle_gateway import OracleDiscoveryResult
from oracle_relationship_discovery.gui.services.runs import AnalysisExecutor
from oracle_relationship_discovery.models import AnalysisStats, SchemaSummary
from oracle_relationship_discovery.output.csv_report import FIELDS

_CONNECTION = {
    "host": "db.example.invalid",
    "port": 1521,
    "service_name": "FAKE_SERVICE",
    "username": "FAKE_USER",
    "password": "secret-not-for-logs",
}


class _Resource:
    @contextmanager
    def acquire(self, _timeout_seconds: int):
        yield object()

    def close(self) -> None:
        pass


class _Gateway:
    def __init__(self) -> None:
        self.calls = 0

    def verify_and_discover(self, _credentials):
        self.calls += 1
        return OracleDiscoveryResult((SchemaSummary("APP", 1, 2),), _Resource())


class _ArtifactExecutor(AnalysisExecutor):
    def __init__(self, root: Path, *, corrupt: str | None = None) -> None:
        self.root = root
        self.corrupt = corrupt
        self.calls = 0

    def execute(self, **kwargs):
        self.calls += 1
        run_id = kwargs["run_id"]
        run = self.root / run_id
        (run / "erd").mkdir(parents=True)
        csv_text = ",".join(FIELDS) + "\n"
        html_text = "<!doctype html><html><body>safe report</body></html>"
        dbml_text = """// Generated by ReliFinder. Inferred logical relationships; not declared Oracle constraints.
// Minimum confidence: 80
// Scope: full
// Eligible after filters/limit: 4
// Rendered DBML references: 3
// Unknown cardinality omitted: 1

Project ReliFinder_ERD {
  database_type: 'Oracle'
}
Table APP.PARENT {
  ID NUMBER [pk]
}
"""
        (run / "relationships.csv").write_text(csv_text, encoding="utf-8-sig")
        (run / "relationship-report.html").write_text(html_text, encoding="utf-8")
        (run / "erd" / "full.dbml").write_text(dbml_text, encoding="utf-8")
        if self.corrupt == "csv":
            (run / "relationships.csv").write_text("not a report", encoding="utf-8")
        if self.corrupt == "html":
            (run / "relationship-report.html").write_text("not html", encoding="utf-8")
        if self.corrupt == "dbml":
            (run / "erd" / "full.dbml").write_text("", encoding="utf-8")
        return AnalysisResult(
            AnalysisStats(1, 1, 2, 4, 3, 0),
            relationships_in_report=3,
            mode="metadata-only",
            elapsed_seconds=0.01,
            run_directory=run,
        )


def _completed_run(client: TestClient) -> tuple[str, str]:
    connection = client.post("/api/connections", json=_CONNECTION).json()["connection_id"]
    response = client.post(
        "/api/runs",
        json={
            "connection_id": connection,
            "schemas": ["APP"],
            "configuration": {"profile": "BALANCED"},
        },
    )
    run_id = response.json()["run_id"]
    deadline = time.monotonic() + 2
    while time.monotonic() < deadline:
        if client.get(f"/api/runs/{run_id}").json()["state"] == "COMPLETED":
            return connection, run_id
        time.sleep(0.01)
    raise AssertionError("run did not complete")


def test_artifact_manifest_and_exact_streamed_responses(tmp_path: Path) -> None:
    gateway = _Gateway()
    executor = _ArtifactExecutor(tmp_path)
    with TestClient(create_app(gateway=gateway, analysis_executor=executor)) as client:
        connection_id, run_id = _completed_run(client)
        assert client.delete(f"/api/connections/{connection_id}").status_code == 204
        listing = client.get(f"/api/runs/{run_id}/artifacts")
        csv_response = client.get(f"/api/runs/{run_id}/artifacts/relationships-csv")
        html_response = client.get(f"/api/runs/{run_id}/artifacts/analysis-html")
        dbml_response = client.get(f"/api/runs/{run_id}/artifacts/erd-dbml")
        exact_csv = (tmp_path / run_id / "relationships.csv").read_bytes()

    assert listing.status_code == 200
    artifacts = {item["id"]: item for item in listing.json()["artifacts"]}
    assert set(artifacts) == {"relationships-csv", "analysis-html", "erd-dbml"}
    assert all(item["available"] and item["size_bytes"] > 0 for item in artifacts.values())
    assert (
        artifacts["erd-dbml"]
        | {
            "scope": "full",
            "min_confidence": 80,
            "eligible_relationships": 4,
            "rendered_relationships": 3,
            "unknown_cardinality_omitted": 1,
        }
        == artifacts["erd-dbml"]
    )
    assert csv_response.content == exact_csv
    assert csv_response.headers["content-type"].startswith("text/csv")
    assert 'attachment; filename="relationships.csv"' == csv_response.headers["content-disposition"]
    assert html_response.text.startswith("<!doctype html>")
    assert html_response.headers["content-disposition"].startswith("inline;")
    assert "default-src 'none'" in html_response.headers["content-security-policy"]
    assert "connect-src 'none'" in html_response.headers["content-security-policy"]
    assert dbml_response.text.startswith("// Generated by ReliFinder")
    assert dbml_response.headers["content-type"].startswith("text/plain")
    assert gateway.calls == 1
    assert executor.calls == 1


def test_download_disposition_and_ids_cannot_traverse_or_cross_runs(tmp_path: Path) -> None:
    with TestClient(
        create_app(gateway=_Gateway(), analysis_executor=_ArtifactExecutor(tmp_path))
    ) as client:
        _, first = _completed_run(client)
        _, second = _completed_run(client)
        download = client.get(f"/api/runs/{first}/artifacts/erd-dbml?download=true")
        traversal = client.get(f"/api/runs/{first}/artifacts/..%2F..%2Fsecret")
        absolute = client.get(f"/api/runs/{first}/artifacts/C:%5CWindows")
        wrong_run_path = client.get(f"/api/runs/{first}/artifacts/{second}%2Ferd-dbml")

    assert download.status_code == 200
    assert download.headers["content-disposition"] == 'attachment; filename="full.dbml"'
    assert traversal.status_code == 404
    assert absolute.status_code == 404
    assert wrong_run_path.status_code == 404
    assert str(tmp_path) not in traversal.text + absolute.text + wrong_run_path.text


def test_missing_and_corrupt_artifacts_are_not_downloadable(tmp_path: Path) -> None:
    executor = _ArtifactExecutor(tmp_path, corrupt="dbml")
    with TestClient(create_app(gateway=_Gateway(), analysis_executor=executor)) as client:
        _, run_id = _completed_run(client)
        run = tmp_path / run_id
        (run / "relationships.csv").unlink()
        listing = client.get(f"/api/runs/{run_id}/artifacts").json()["artifacts"]
        csv_response = client.get(f"/api/runs/{run_id}/artifacts/relationships-csv")
        dbml_response = client.get(f"/api/runs/{run_id}/artifacts/erd-dbml")

    by_id = {item["id"]: item for item in listing}
    assert by_id["relationships-csv"]["available"] is False
    assert by_id["erd-dbml"]["available"] is False
    assert csv_response.status_code == 409
    assert dbml_response.status_code == 409
    assert csv_response.json()["error"]["code"] == "ARTIFACT_UNAVAILABLE"


def test_corrupt_csv_and_html_are_withheld(tmp_path: Path) -> None:
    for kind, artifact_id in (("csv", "relationships-csv"), ("html", "analysis-html")):
        root = tmp_path / kind
        with TestClient(
            create_app(gateway=_Gateway(), analysis_executor=_ArtifactExecutor(root, corrupt=kind))
        ) as client:
            _, run_id = _completed_run(client)
            listing = client.get(f"/api/runs/{run_id}/artifacts").json()["artifacts"]
            response = client.get(f"/api/runs/{run_id}/artifacts/{artifact_id}")

        metadata = next(item for item in listing if item["id"] == artifact_id)
        assert metadata["available"] is False
        assert response.status_code == 409
        assert str(root) not in response.text


def test_non_completed_and_invalid_run_do_not_expose_artifacts(tmp_path: Path) -> None:
    with TestClient(
        create_app(gateway=_Gateway(), analysis_executor=_ArtifactExecutor(tmp_path))
    ) as client:
        invalid = client.get("/api/runs/not-a-run/artifacts")

    assert invalid.status_code == 404
    assert invalid.json()["error"]["code"] == "RUN_NOT_FOUND"
