"""DBML exporter with Oracle-preserving types and explainable references."""

import re
from pathlib import Path

from oracle_relationship_discovery.output.erd_models import ErdExportOptions, ErdModel, ErdTable

_SAFE_IDENTIFIER = re.compile(r"^[A-Za-z_][A-Za-z0-9_$#]*$")
_SAFE_TYPE = re.compile(r"^[A-Za-z][A-Za-z0-9_]*(?:\([0-9]+(?:,[0-9]+)?\))?$")


def dbml_identifier(value: str) -> str:
    if not value or any(ord(char) < 32 for char in value):
        raise ValueError(f"Invalid DBML identifier: {value!r}")
    return value if _SAFE_IDENTIFIER.fullmatch(value) else '"' + value.replace('"', '\\"') + '"'


def oracle_type(column) -> str:
    kind = column.data_type.upper().strip()
    if kind == "NUMBER" and column.precision is not None:
        kind += (
            f"({column.precision},{column.scale})"
            if column.scale is not None
            else f"({column.precision})"
        )
    elif (
        kind in {"VARCHAR2", "VARCHAR", "NVARCHAR2", "CHAR", "NCHAR", "RAW"} and column.data_length
    ):
        kind += f"({column.data_length})"
    return kind if _SAFE_TYPE.fullmatch(kind) else '"' + kind.replace('"', '\\"') + '"'


def _qualified(schema: str, table: str, column: str | None = None) -> str:
    value = f"{dbml_identifier(schema)}.{dbml_identifier(table)}"
    return f"{value}.{dbml_identifier(column)}" if column else value


def _constraint_lines(table: ErdTable) -> list[str]:
    groups: dict[str, tuple[str, list[str]]] = {}
    for column in sorted(table.columns, key=lambda item: item.position):
        for name in column.composite_constraints:
            kind = "pk" if name in column.pk_constraints else "unique"
            groups.setdefault(name, (kind, []))[1].append(column.name)
    if not groups:
        return []
    lines = ["  indexes {"]
    for name, (kind, columns) in sorted(groups.items()):
        joined = ", ".join(dbml_identifier(column) for column in columns)
        safe_name = name.replace("'", "\\'")
        lines.append(f"    ({joined}) [{kind}, name: '{safe_name}']")
    lines.append("  }")
    return lines


class DbmlExporter:
    def export(
        self,
        model: ErdModel,
        destination: Path,
        options: ErdExportOptions,
        *,
        external_to_schema: str | None = None,
    ) -> int:
        lines = [
            "// Generated by ReliFinder. Inferred logical relationships; not declared Oracle constraints.",
            f"// Minimum confidence: {options.min_confidence:g}",
            f"// Scope: {options.scope}",
            "",
            "Project ReliFinder_ERD {",
            "  database_type: 'Oracle'",
            "  Note: 'Read-only inference output. Review before operational use.'",
            "}",
            "",
        ]
        for table in sorted(model.tables, key=lambda item: item.key):
            lines.append(f"Table {_qualified(table.schema, table.name)} {{")
            if external_to_schema and table.schema != external_to_schema:
                lines.append(f"  Note: 'External table referenced by {external_to_schema}'")
            for column in sorted(table.columns, key=lambda item: (item.position, item.name)):
                attrs = []
                if column.pk_constraints and not column.composite_constraints:
                    attrs.append("pk")
                elif column.unique_constraints and not column.composite_constraints:
                    attrs.append("unique")
                if not column.nullable:
                    attrs.append("not null")
                suffix = f" [{', '.join(attrs)}]" if attrs else ""
                lines.append(f"  {dbml_identifier(column.name)} {oracle_type(column)}{suffix}")
            lines.extend(_constraint_lines(table))
            lines.extend(["}", ""])
        unknown = 0
        for rel in model.relationships:
            match = "n/a" if rel.match_ratio is None else f"{rel.match_ratio:.2%}"
            lines.extend(
                [
                    "// ReliFinder evidence:",
                    "// Relationship type: inferred logical",
                    f"// Confidence: {rel.confidence_score:g} ({rel.confidence_label})",
                    f"// Sample match: {match}",
                    f"// Cardinality: {rel.cardinality}",
                    f"// Validation status: {rel.validation_status or 'unknown'}",
                ]
            )
            normalized = rel.cardinality.upper().replace("-", "_").replace(" ", "_")
            operator = {"MANY_TO_ONE": ">", "ONE_TO_MANY": "<", "ONE_TO_ONE": "-"}.get(normalized)
            if operator:
                source = _qualified(rel.source_schema, rel.source_table, rel.source_column)
                target = _qualified(rel.target_schema, rel.target_table, rel.target_column)
                # DBML treats the second endpoint of one-to-one as the FK column.
                left, right = (target, source) if normalized == "ONE_TO_ONE" else (source, target)
                lines.append(f"Ref: {left} {operator} {right}")
            else:
                unknown += 1
                lines.append(
                    "// Ref omitted: DBML has no neutral operator for unknown cardinality."
                )
            lines.append("")
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
        return unknown
