import { http, HttpResponse } from "msw";
import { render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { createMemoryRouter, RouterProvider } from "react-router-dom";
import { beforeEach, describe, expect, it, vi } from "vitest";

import type { ArtifactListResponse } from "../../api/client";
import { AppProviders } from "../../app/providers/app-providers";
import { appRoutes } from "../../app/router/routes";
import { server } from "../../test/mocks/server";

const runId = "export-run-123456789012345678901234";
const dbml = "// Generated by ReliFinder\nProject ReliFinder_ERD {\n}\n";
const completeArtifacts: ArtifactListResponse = {
  run_id: runId,
  artifacts: [
    {
      id: "relationships-csv",
      type: "csv",
      filename: "relationships.csv",
      available: true,
      size_bytes: 2048,
    },
    {
      id: "analysis-html",
      type: "html",
      filename: "relationship-report.html",
      available: true,
      size_bytes: 4096,
    },
    {
      id: "erd-dbml",
      type: "dbml",
      filename: "full.dbml",
      available: true,
      size_bytes: dbml.length,
      scope: "full",
      min_confidence: 80,
      eligible_relationships: 5,
      rendered_relationships: 4,
      unknown_cardinality_omitted: 1,
    },
  ],
};

function installApi(payload = completeArtifacts) {
  server.use(
    http.get("/api/runs/:runId/artifacts", () => HttpResponse.json(payload)),
    http.get(
      "/api/runs/:runId/artifacts/erd-dbml",
      () =>
        new HttpResponse(dbml, {
          headers: { "Content-Length": String(dbml.length), "Content-Type": "text/plain" },
        }),
    ),
  );
}

function renderExports() {
  return render(
    <AppProviders>
      <RouterProvider
        router={createMemoryRouter(appRoutes, {
          initialEntries: [`/exports?run=${runId}`],
        })}
      />
    </AppProviders>,
  );
}

beforeEach(() => {
  Object.defineProperty(navigator, "clipboard", {
    configurable: true,
    value: { writeText: vi.fn().mockResolvedValue(undefined) },
  });
});

describe("completed-run exports", () => {
  it("lists exact CSV/HTML/DBML actions and explains DBML omissions", async () => {
    installApi();
    renderExports();

    expect(await screen.findByRole("heading", { name: "Artifacts & DBML" })).toBeInTheDocument();
    const csv = screen.getByRole("link", { name: "Download CSV" });
    expect(csv).toHaveAttribute(
      "href",
      `/api/runs/${runId}/artifacts/relationships-csv?download=true`,
    );
    const openReport = screen.getByRole("link", { name: "Open Report" });
    expect(openReport).toHaveAttribute("href", `/api/runs/${runId}/artifacts/analysis-html`);
    expect(openReport).toHaveAttribute("target", "_blank");
    expect(screen.getByRole("link", { name: "Download HTML" })).toHaveAttribute(
      "href",
      `/api/runs/${runId}/artifacts/analysis-html?download=true`,
    );
    expect(await screen.findByRole("heading", { name: "DBML Code" })).toBeInTheDocument();
    expect(
      screen.getByText(
        (_content, element) =>
          element?.tagName === "CODE" &&
          element.textContent?.includes("Project ReliFinder_ERD {") === true,
      ),
    ).toBeInTheDocument();
    expect(screen.getByText(/DBML references: 4/)).toBeInTheDocument();
    expect(screen.getByText(/Unknown-cardinality relationships omitted: 1/)).toBeInTheDocument();
    expect(screen.getByText(/not the current transient GUI filter/i)).toBeInTheDocument();
    expect(screen.getByRole("link", { name: "Open dbdiagram" })).toHaveAttribute(
      "href",
      "https://dbdiagram.io/",
    );
    expect(screen.getAllByRole("link", { name: "Download DBML" })[0]).toHaveAttribute(
      "href",
      `/api/runs/${runId}/artifacts/erd-dbml?download=true`,
    );
  });

  it("copies DBML only after explicit user action", async () => {
    const user = userEvent.setup();
    const writeText = vi.fn().mockResolvedValue(undefined);
    Object.defineProperty(navigator, "clipboard", {
      configurable: true,
      value: { writeText },
    });
    installApi();
    renderExports();
    await screen.findByRole("heading", { name: "DBML Code" });

    await user.click(screen.getByRole("button", { name: "Copy" }));

    expect(writeText).toHaveBeenCalledWith(dbml);
    expect(await screen.findByRole("button", { name: "Copied" })).toBeInTheDocument();
  });
  it("handles clipboard denial without losing the viewer", async () => {
    const user = userEvent.setup();
    Object.defineProperty(navigator, "clipboard", {
      configurable: true,
      value: { writeText: vi.fn().mockRejectedValue(new Error("denied")) },
    });
    installApi();
    renderExports();
    await screen.findByRole("heading", { name: "DBML Code" });

    await user.click(screen.getByRole("button", { name: "Copy" }));

    expect(await screen.findByRole("alert")).toHaveTextContent(/clipboard access failed/i);
    expect(
      screen.getByText(
        (_content, element) =>
          element?.tagName === "CODE" &&
          element.textContent?.includes("Project ReliFinder_ERD {") === true,
      ),
    ).toBeInTheDocument();
  });

  it("keeps large DBML downloadable while declining an oversized preview", async () => {
    installApi();
    server.use(
      http.get(
        "/api/runs/:runId/artifacts/erd-dbml",
        () =>
          new HttpResponse("preview skipped", {
            headers: { "Content-Length": "6000000", "Content-Type": "text/plain" },
          }),
      ),
    );
    renderExports();

    expect(await screen.findByRole("alert")).toHaveTextContent(
      /DBML is too large to preview; download it instead/i,
    );
    expect(screen.getAllByRole("link", { name: "Download DBML" }).length).toBeGreaterThan(0);
  });
  it("shows unavailable artifacts without enabling unsafe actions", async () => {
    installApi({
      run_id: runId,
      artifacts: completeArtifacts.artifacts.map((artifact) =>
        artifact.type === "dbml" ? { ...artifact, available: false, size_bytes: null } : artifact,
      ),
    });
    renderExports();

    expect(await screen.findByText(/DBML was not generated/i)).toBeInTheDocument();
    expect(screen.getByText("Not generated or invalid")).toBeInTheDocument();
    expect(screen.queryByRole("button", { name: "Copy" })).not.toBeInTheDocument();
  });

  it("does not enable exports for a failed or incomplete run", async () => {
    server.use(
      http.get("/api/runs/:runId/artifacts", () =>
        HttpResponse.json(
          {
            error: {
              code: "RUN_NOT_COMPLETED",
              message: "Artifacts are available only for a completed analysis run.",
            },
          },
          { status: 409 },
        ),
      ),
    );
    renderExports();

    expect(await screen.findByRole("heading", { name: "Exports unavailable" })).toBeInTheDocument();
    expect(screen.getByText(/only for a completed analysis run/i)).toBeInTheDocument();
    expect(screen.queryByRole("link", { name: /Download/ })).not.toBeInTheDocument();
  });
});
